DATA COllECTION

In [7]:
!pip install pymysql

Requirement already satisfied: pymysql in c:\users\s.palakorn\anaconda3\lib\site-packages (1.1.0)

Config DB credential
default for input DB info

In [12]:
import os

class Config:
    MYSQL_HOST = '...' #IP address for DB
    MYSQL_PORT = 3306            # default for port MySQL
    MYSQL_USER = '...'
    MYSQL_PASSWORD = '...'
    MYSQL_DB = '...'
    MYSQL_CHARSET = '...'

In [13]:
print(Config.MYSQL_PORT) #print to check port

3306

Create connection to Data Base

In [40]:
import pymysql
connection = pymysql.connect(host=Config.MYSQL_HOST,
                             port=Config.MYSQL_PORT,
                             user=Config.MYSQL_USER,
                             password=Config.MYSQL_PASSWORD,
                             db=Config.MYSQL_DB,
                             charset=Config.MYSQL_CHARSET,
                             cursorclass=pymysql.cursors.DictCursor)

In [15]:
connection

List Tables
Watching data in the table
cursor is appied for running SQL command.

In [16]:
cursor = connection.cursor() #the cursor is a command for a specific database fuction in this case is used for pymysql.
cursor.execute("show tables;") #Command with SQL language
table = cursor.fetchall() #to keep value after commanding in table variable
cursor.close() #if we using these method we have always to close it.
print(table) #it will display all table in Data base that we connected {first is name of DB : Second is name of table}.

[{'Tables_in_r2de2': 'audible_data'}, {'Tables_in_r2de2': 'audible_transaction'}]

we can use "with" instead of above method and we no need to use cursor.close() if we use "with"

In [18]:
with connection.cursor() as cursor:
    cursor.execute("SELECT * FROM audible_data;") #Command with SQL language
    result =  cursor.fetchall() #using for reading table in data base with cursor command

print("numner of rows: ", len(result)) #len rows in the table

numner of rows:  2269

In [20]:
result # it will show as list of dictionary

In [21]:
type(result)

list

Therefore, we will convert list of dictionalry to pandas for easy to read data

In [22]:
import pandas as pd

In [34]:
audible_data = pd.DataFrame(result) #set list of dictionary from result to Dataframe in pandas function

In [37]:
audible_data

,Book Title,Book Subtitle,Book Author,Book Narrator,Audio Runtime,Audiobook_Type,Categories,Rating,Total No. of Ratings,Price
Book_ID,,,,,,,,,,
1,Bamboozled by Jesus,How God Tricked Me into the Life of My Dreams,Yvonne Orji,Yvonne Orji,6 hrs and 31 mins,Unabridged Audiobook,Biographies & Memoirs,5,47.0,$29.65
2,Sixth Realm Part 1,"A LitRPG Fantasy Series (The Ten Realms, Book 6)",Michael Chatfield,Neil Hellegers,13 hrs and 33 mins,Unabridged Audiobook,Science Fiction & Fantasy,4.5,98.0,$24.95
3,Go Tell the Bees That I Am Gone,"Outlander, Book 9",Diana Gabaldon,Davina Porter,27 hrs and 30 mins,Unabridged Audiobook,Science Fiction & Fantasy,None,NaN,$41.99
4,How the Word Is Passed,A Reckoning with the History of Slavery Across...,Clint Smith,Clint Smith,10 hrs and 7 mins,Unabridged Audiobook,History,None,NaN,$29.65
5,The Devil May Dance,A Novel,Jake Tapper,Rob Shapiro,10 hrs and 12 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.5,108.0,$29.65
...,...,...,...,...,...,...,...,...,...,...
2265,Kama Sutra,Become a Master of the Art of Love Making. Tan...,Eva Becker,ChasMandala,3 hrs and 29 mins,Unabridged Audiobook,Erotica,5,203.0,$14.95
2266,Meditación Práctica para Principiantes [Prac...,Una guía para principiantes para aliviar la an...,Taylor Knox,William Ditilio,3 hrs and 14 mins,Unabridged Audiobook,Health & Wellness,5,203.0,$14.95
2267,Forgotten,"The Untold Story of D-day's Black Heroes, at H...",Linda Hervieux,Ron Butler,9 hrs and 33 mins,Unabridged Audiobook,History,4.6,70.0,$24.95
2268,The Missing,None,Daisy Pearce,Karen Cass,10 hrs and 18 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.2,141.0,$30.09
2269,Becoming,None,Michelle Obama,Michelle Obama,19 hrs and 3 mins,Unabridged Audiobook,Biographies & Memoirs,4.9,167195.0,$35.71

In [36]:
audible_data = audible_data.set_index("Book_ID") #set index from index row(0-n) to "Book_ID" start form 1 to n

Alternative way and short way
audible_data = pd.DataFrame(result, index_col = "Book_ID")
Thus, we can use as the starting set to pandas

Another way to covert list of dictionary by using SQL in python fuction with pandas below this

but sometime we have to re-connected code again from connection DB to excute SQL method, it is disadvantage if we don't use data wearhouse.

In [41]:
sql = "SELECT * FROM audible_transaction" #set SQL command in sql variable
audible_transaction = pd.read_sql(sql, connection) #using pandas with .read_sql function to excute
audible_transaction

                  timestamp   user_id  book_id                   country
0       2021-05-01 00:00:01  ad8eca41     1584                  Portugal
1       2021-05-01 00:00:03  561b26c1      829  United States of America
2       2021-05-01 00:00:04  81f149e5     1391                     Japan
3       2021-05-01 00:00:07  4f218413     1586                    Taiwan
4       2021-05-01 00:00:18  a4066781      300  United States of America
...                     ...       ...      ...                       ...
1998816 2021-07-31 23:59:47  72da1411      600                  Portugal
1998817 2021-07-31 23:59:48  620c27c8      462                Montenegro
1998818 2021-07-31 23:59:55  84fe88ab     1656  United States of America
1998819 2021-07-31 23:59:57  fd6cc4fc      522  United States of America
1998820 2021-07-31 23:59:59  9f4d5e3b      110  United States of America

[1998821 rows x 4 columns]

Join table: audible_transaction and audible_date togather
- audible_transaction: book_id
- audible_data: Book_ID
book_id is a key to join table

In [43]:
transaction = audible_transaction.merge(audible_data, how = "left", left_on= "book_id", right_on= "Book_ID")

In [44]:
transaction

,timestamp,user_id,book_id,country,Book Title,Book Subtitle,Book Author,Book Narrator,Audio Runtime,Audiobook_Type,Categories,Rating,Total No. of Ratings,Price
0,2021-05-01 00:00:01,ad8eca41,1584,Portugal,Sycamore Row,None,John Grisham,Michael Beck,20 hrs and 46 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,25863.0,$35.00
1,2021-05-01 00:00:03,561b26c1,829,United States of America,The 5 Love Languages of Children,The Secret to Loving Children Effectively,Gary Chapman,Chris Fabry,5 hrs and 48 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,2441.0,$19.59
2,2021-05-01 00:00:04,81f149e5,1391,Japan,The Guardians,A Novel,John Grisham,Michael Beck,11 hrs and 50 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,26781.0,$31.50
3,2021-05-01 00:00:07,4f218413,1586,Taiwan,How to Be a 3% Man,None,Corey Wayne,Corey Wayne,7 hrs and 33 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,11459.0,$19.95
4,2021-05-01 00:00:18,a4066781,300,United States of America,Napoleon Hill's Outwitting the Devil,The Secret to Freedom and Success,Napoleon Hill,Dan John Miller,5 hrs and 51 mins,Unabridged Audiobook,Business & Careers,4.8,9305.0,$17.49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1998816,2021-07-31 23:59:47,72da1411,600,Portugal,The Time of Contempt,"The Witcher, Book 2",Andrzej Sapkowski,Peter Kenny,11 hrs and 55 mins,Unabridged Audiobook,Science Fiction & Fantasy,4.7,14344.0,$25.08
1998817,2021-07-31 23:59:48,620c27c8,462,Montenegro,Endurance,Shackleton's Incredible Voyage,Alfred Lansing,Simon Prebble,10 hrs and 20 mins,Unabridged Audiobook,History,4.7,18764.0,$24.95
1998818,2021-07-31 23:59:55,84fe88ab,1656,United States of America,The Spy and the Traitor,The Greatest Espionage Story of the Cold War,Ben Macintyre,John Lee,13 hrs and 20 mins,Unabridged Audiobook,Biographies & Memoirs,4.8,7150.0,$31.95
1998819,2021-07-31 23:59:57,fd6cc4fc,522,United States of America,Lilac Girls,A Novel,Martha Hall Kelly,Cassandra Campbell,17 hrs and 30 mins,Unabridged Audiobook,Literature & Fiction,4.7,19401.0,$31.50
1998820,2021-07-31 23:59:59,9f4d5e3b,110,United States of America,Unfu*k Yourself,Get Out of Your Head and into Your Life,Gary John Bishop,Gary John Bishop,3 hrs and 24 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.6,73022.0,$20.52

Now we got two table already but in col price stil getting string with $ we need int to cal next step so that we will let $ out.

Before that we gonna import API by using request function to get data about price rate (THB)

In [45]:
import requests

web bowser if we have the link it should be json URL: https://r2de2-workshop-vmftiryt6q-ts.a.run.app/usd_thb_conversion_rate

In [55]:
url = "https://r2de2-workshop-vmftiryt6q-ts.a.run.app/usd_thb_conversion_rate"
r = requests.get(url) # a get request to the API
result_conversion_rate =  r.json() #set data to json

In [56]:
r.text #reading url as text

'{"conversion_rate":{"2021-08-12":33.084,"2021-08-11":33.145,"2021-08-10":33.46,"2021-08-09":33.464,"2021-08-08":33.395,"2021-08-07":33.422,"2021-08-06":33.45,"2021-08-05":33.263,"2021-08-04":33.137,"2021-08-03":33.022,"2021-08-02":32.957,"2021-08-01":32.895,"2021-07-31":32.887,"2021-07-30":32.887,"2021-07-29":32.87,"2021-07-28":32.82,"2021-07-27":32.937,"2021-07-26":32.929,"2021-07-25":32.94,"2021-07-24":32.963,"2021-07-23":32.928,"2021-07-22":32.887,"2021-07-21":32.857,"2021-07-20":32.829,"2021-07-19":32.854,"2021-07-18":32.807,"2021-07-17":32.795,"2021-07-16":32.783,"2021-07-15":32.686,"2021-07-14":32.605,"2021-07-13":32.654,"2021-07-12":32.664,"2021-07-11":32.506,"2021-07-10":32.482,"2021-07-09":32.512,"2021-07-08":32.534,"2021-07-07":32.334,"2021-07-06":32.271,"2021-07-05":32.112,"2021-07-04":32.136,"2021-07-03":32.125,"2021-07-02":32.126,"2021-07-01":32.073,"2021-06-30":32.029,"2021-06-29":32.108,"2021-06-28":31.918,"2021-06-27":31.785,"2021-06-26":31.816,"2021-06-25":31.816,"2021-06-24":31.898,"2021-06-23":31.825,"2021-06-22":31.681,"2021-06-21":31.617,"2021-06-20":31.461,"2021-06-19":31.437,"2021-06-18":31.439,"2021-06-17":31.422,"2021-06-16":31.297,"2021-06-15":31.162,"2021-06-14":31.117,"2021-06-13":31.077,"2021-06-12":31.074,"2021-06-11":31.092,"2021-06-10":31.14,"2021-06-09":31.167,"2021-06-08":31.202,"2021-06-07":31.176,"2021-06-06":31.133,"2021-06-05":31.125,"2021-06-04":31.125,"2021-06-03":31.209,"2021-06-02":31.108,"2021-06-01":31.169,"2021-05-31":31.193,"2021-05-30":31.238,"2021-05-29":31.252,"2021-05-28":31.257,"2021-05-27":31.297,"2021-05-26":31.281,"2021-05-25":31.328,"2021-05-24":31.323,"2021-05-23":31.37,"2021-05-22":31.361,"2021-05-21":31.361,"2021-05-20":31.378,"2021-05-19":31.413,"2021-05-18":31.42,"2021-05-17":31.492,"2021-05-16":31.365,"2021-05-15":31.33,"2021-05-14":31.33,"2021-05-13":31.344,"2021-05-12":31.304,"2021-05-11":31.158,"2021-05-10":31.107,"2021-05-09":31.033,"2021-05-08":31.042,"2021-05-07":31.042,"2021-05-06":31.226,"2021-05-05":31.13,"2021-05-04":31.188,"2021-05-03":31.132,"2021-05-02":31.122,"2021-05-01":31.14,"2021-04-30":31.139,"2021-04-29":31.197,"2021-04-28":31.344,"2021-04-27":31.355,"2021-04-26":31.427,"2021-04-25":31.421,"2021-04-24":31.411,"2021-04-23":31.412,"2021-04-22":31.378,"2021-04-21":31.3,"2021-04-20":31.281,"2021-04-19":31.203,"2021-04-18":31.226,"2021-04-17":31.204,"2021-04-16":31.203,"2021-04-15":31.165,"2021-04-14":31.329,"2021-04-13":31.496,"2021-04-12":31.482,"2021-04-11":31.462,"2021-04-10":31.454,"2021-04-09":31.451,"2021-04-08":31.433,"2021-04-07":31.387,"2021-04-06":31.288,"2021-04-05":31.342,"2021-04-04":31.244,"2021-04-03":31.256,"2021-04-02":31.29,"2021-04-01":31.194}}'

In [57]:
r.status_code # to check status code with API if it show 200 it mean that status success

200

In [58]:
result_conversion_rate # now we get data from API to Dictionary

{'conversion_rate': {'2021-08-12': 33.084,
  '2021-08-11': 33.145,
  '2021-08-10': 33.46,
  '2021-08-09': 33.464,
  '2021-08-08': 33.395,
  '2021-08-07': 33.422,
  '2021-08-06': 33.45,
  '2021-08-05': 33.263,
  '2021-08-04': 33.137,
  '2021-08-03': 33.022,
  '2021-08-02': 32.957,
  '2021-08-01': 32.895,
  '2021-07-31': 32.887,
  '2021-07-30': 32.887,
  '2021-07-29': 32.87,
  '2021-07-28': 32.82,
  '2021-07-27': 32.937,
  '2021-07-26': 32.929,
  '2021-07-25': 32.94,
  '2021-07-24': 32.963,
  '2021-07-23': 32.928,
  '2021-07-22': 32.887,
  '2021-07-21': 32.857,
  '2021-07-20': 32.829,
  '2021-07-19': 32.854,
  '2021-07-18': 32.807,
  '2021-07-17': 32.795,
  '2021-07-16': 32.783,
  '2021-07-15': 32.686,
  '2021-07-14': 32.605,
  '2021-07-13': 32.654,
  '2021-07-12': 32.664,
  '2021-07-11': 32.506,
  '2021-07-10': 32.482,
  '2021-07-09': 32.512,
  '2021-07-08': 32.534,
  '2021-07-07': 32.334,
  '2021-07-06': 32.271,
  '2021-07-05': 32.112,
  '2021-07-04': 32.136,
  '2021-07-03': 32.125,
  '2021-07-02': 32.126,
  '2021-07-01': 32.073,
  '2021-06-30': 32.029,
  '2021-06-29': 32.108,
  '2021-06-28': 31.918,
  '2021-06-27': 31.785,
  '2021-06-26': 31.816,
  '2021-06-25': 31.816,
  '2021-06-24': 31.898,
  '2021-06-23': 31.825,
  '2021-06-22': 31.681,
  '2021-06-21': 31.617,
  '2021-06-20': 31.461,
  '2021-06-19': 31.437,
  '2021-06-18': 31.439,
  '2021-06-17': 31.422,
  '2021-06-16': 31.297,
  '2021-06-15': 31.162,
  '2021-06-14': 31.117,
  '2021-06-13': 31.077,
  '2021-06-12': 31.074,
  '2021-06-11': 31.092,
  '2021-06-10': 31.14,
  '2021-06-09': 31.167,
  '2021-06-08': 31.202,
  '2021-06-07': 31.176,
  '2021-06-06': 31.133,
  '2021-06-05': 31.125,
  '2021-06-04': 31.125,
  '2021-06-03': 31.209,
  '2021-06-02': 31.108,
  '2021-06-01': 31.169,
  '2021-05-31': 31.193,
  '2021-05-30': 31.238,
  '2021-05-29': 31.252,
  '2021-05-28': 31.257,
  '2021-05-27': 31.297,
  '2021-05-26': 31.281,
  '2021-05-25': 31.328,
  '2021-05-24': 31.323,
  '2021-05-23': 31.37,
  '2021-05-22': 31.361,
  '2021-05-21': 31.361,
  '2021-05-20': 31.378,
  '2021-05-19': 31.413,
  '2021-05-18': 31.42,
  '2021-05-17': 31.492,
  '2021-05-16': 31.365,
  '2021-05-15': 31.33,
  '2021-05-14': 31.33,
  '2021-05-13': 31.344,
  '2021-05-12': 31.304,
  '2021-05-11': 31.158,
  '2021-05-10': 31.107,
  '2021-05-09': 31.033,
  '2021-05-08': 31.042,
  '2021-05-07': 31.042,
  '2021-05-06': 31.226,
  '2021-05-05': 31.13,
  '2021-05-04': 31.188,
  '2021-05-03': 31.132,
  '2021-05-02': 31.122,
  '2021-05-01': 31.14,
  '2021-04-30': 31.139,
  '2021-04-29': 31.197,
  '2021-04-28': 31.344,
  '2021-04-27': 31.355,
  '2021-04-26': 31.427,
  '2021-04-25': 31.421,
  '2021-04-24': 31.411,
  '2021-04-23': 31.412,
  '2021-04-22': 31.378,
  '2021-04-21': 31.3,
  '2021-04-20': 31.281,
  '2021-04-19': 31.203,
  '2021-04-18': 31.226,
  '2021-04-17': 31.204,
  '2021-04-16': 31.203,
  '2021-04-15': 31.165,
  '2021-04-14': 31.329,
  '2021-04-13': 31.496,
  '2021-04-12': 31.482,
  '2021-04-11': 31.462,
  '2021-04-10': 31.454,
  '2021-04-09': 31.451,
  '2021-04-08': 31.433,
  '2021-04-07': 31.387,
  '2021-04-06': 31.288,
  '2021-04-05': 31.342,
  '2021-04-04': 31.244,
  '2021-04-03': 31.256,
  '2021-04-02': 31.29,
  '2021-04-01': 31.194}}

let check type of data

In [59]:
print(type(result_conversion_rate))
assert isinstance(result_conversion_rate, dict) #assert is to check True or False mean that result_conversion_rate is dictionary or not

<class 'dict'>

After we got data coversion_rate for API and make it to dictionary now we have to set it into Pandas again for easy way to do in the table

In [60]:
conversion_rate = pd.DataFrame(result_conversion_rate)

In [61]:
conversion_rate

            conversion_rate
2021-04-01           31.194
2021-04-02           31.290
2021-04-03           31.256
2021-04-04           31.244
2021-04-05           31.342
...                     ...
2021-08-08           33.395
2021-08-09           33.464
2021-08-10           33.460
2021-08-11           33.145
2021-08-12           33.084

[134 rows x 1 columns]

change index to be column date for comfortable to joint with table transaction

In [62]:
conversion_rate = conversion_rate.reset_index().rename(columns={"index": "date"}) #in first column is index but we dont want index so we will make it to column to easily for joining table
conversion_rate[:3]

         date  conversion_rate
0  2021-04-01           31.194
1  2021-04-02           31.290
2  2021-04-03           31.256

Let's check table both and see how can we use which column to join in this case from conversion_rate table we have date column but in transaction table we have the save column date but
if we watch carefully we will see time-stamp instead therefore we gonna change that column as the same type.

In [63]:
transaction['date'] = transaction['timestamp'] #creating new column but having values as timestamp column
transaction

,timestamp,user_id,book_id,country,Book Title,Book Subtitle,Book Author,Book Narrator,Audio Runtime,Audiobook_Type,Categories,Rating,Total No. of Ratings,Price,date
0,2021-05-01 00:00:01,ad8eca41,1584,Portugal,Sycamore Row,None,John Grisham,Michael Beck,20 hrs and 46 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,25863.0,$35.00,2021-05-01 00:00:01
1,2021-05-01 00:00:03,561b26c1,829,United States of America,The 5 Love Languages of Children,The Secret to Loving Children Effectively,Gary Chapman,Chris Fabry,5 hrs and 48 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,2441.0,$19.59,2021-05-01 00:00:03
2,2021-05-01 00:00:04,81f149e5,1391,Japan,The Guardians,A Novel,John Grisham,Michael Beck,11 hrs and 50 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,26781.0,$31.50,2021-05-01 00:00:04
3,2021-05-01 00:00:07,4f218413,1586,Taiwan,How to Be a 3% Man,None,Corey Wayne,Corey Wayne,7 hrs and 33 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,11459.0,$19.95,2021-05-01 00:00:07
4,2021-05-01 00:00:18,a4066781,300,United States of America,Napoleon Hill's Outwitting the Devil,The Secret to Freedom and Success,Napoleon Hill,Dan John Miller,5 hrs and 51 mins,Unabridged Audiobook,Business & Careers,4.8,9305.0,$17.49,2021-05-01 00:00:18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1998816,2021-07-31 23:59:47,72da1411,600,Portugal,The Time of Contempt,"The Witcher, Book 2",Andrzej Sapkowski,Peter Kenny,11 hrs and 55 mins,Unabridged Audiobook,Science Fiction & Fantasy,4.7,14344.0,$25.08,2021-07-31 23:59:47
1998817,2021-07-31 23:59:48,620c27c8,462,Montenegro,Endurance,Shackleton's Incredible Voyage,Alfred Lansing,Simon Prebble,10 hrs and 20 mins,Unabridged Audiobook,History,4.7,18764.0,$24.95,2021-07-31 23:59:48
1998818,2021-07-31 23:59:55,84fe88ab,1656,United States of America,The Spy and the Traitor,The Greatest Espionage Story of the Cold War,Ben Macintyre,John Lee,13 hrs and 20 mins,Unabridged Audiobook,Biographies & Memoirs,4.8,7150.0,$31.95,2021-07-31 23:59:55
1998819,2021-07-31 23:59:57,fd6cc4fc,522,United States of America,Lilac Girls,A Novel,Martha Hall Kelly,Cassandra Campbell,17 hrs and 30 mins,Unabridged Audiobook,Literature & Fiction,4.7,19401.0,$31.50,2021-07-31 23:59:57
1998820,2021-07-31 23:59:59,9f4d5e3b,110,United States of America,Unfu*k Yourself,Get Out of Your Head and into Your Life,Gary John Bishop,Gary John Bishop,3 hrs and 24 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.6,73022.0,$20.52,2021-07-31 23:59:59

In [64]:
#change date column both table to date types as the same
transaction['date'] = pd.to_datetime(transaction['date']).dt.date
conversion_rate['date'] = pd.to_datetime(conversion_rate['date']).dt.date
transaction.head() # check date colume

,timestamp,user_id,book_id,country,Book Title,Book Subtitle,Book Author,Book Narrator,Audio Runtime,Audiobook_Type,Categories,Rating,Total No. of Ratings,Price,date
0,2021-05-01 00:00:01,ad8eca41,1584,Portugal,Sycamore Row,None,John Grisham,Michael Beck,20 hrs and 46 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,25863.0,$35.00,2021-05-01
1,2021-05-01 00:00:03,561b26c1,829,United States of America,The 5 Love Languages of Children,The Secret to Loving Children Effectively,Gary Chapman,Chris Fabry,5 hrs and 48 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,2441.0,$19.59,2021-05-01
2,2021-05-01 00:00:04,81f149e5,1391,Japan,The Guardians,A Novel,John Grisham,Michael Beck,11 hrs and 50 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,26781.0,$31.50,2021-05-01
3,2021-05-01 00:00:07,4f218413,1586,Taiwan,How to Be a 3% Man,None,Corey Wayne,Corey Wayne,7 hrs and 33 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,11459.0,$19.95,2021-05-01
4,2021-05-01 00:00:18,a4066781,300,United States of America,Napoleon Hill's Outwitting the Devil,The Secret to Freedom and Success,Napoleon Hill,Dan John Miller,5 hrs and 51 mins,Unabridged Audiobook,Business & Careers,4.8,9305.0,$17.49,2021-05-01

In [65]:
conversion_rate.head() #check date colume

         date  conversion_rate
0  2021-04-01           31.194
1  2021-04-02           31.290
2  2021-04-03           31.256
3  2021-04-04           31.244
4  2021-04-05           31.342

denormalize is a large table that alread joined from every table that we want to know and it's appropriate for analysis.
normalize is suitable for data base it mean that there are many small table.

In [82]:
#join two table with date column
#in this case, we already joined three table audible_table(from DB), auduble_transaction(from DB) and coversion_rate(from API)
final_df = transaction.merge(conversion_rate, how = "left", left_on = "date", right_on = "date")
final_df.head()

,timestamp,user_id,book_id,country,Book Title,Book Subtitle,Book Author,Book Narrator,Audio Runtime,Audiobook_Type,Categories,Rating,Total No. of Ratings,Price,date,conversion_rate
0,2021-05-01 00:00:01,ad8eca41,1584,Portugal,Sycamore Row,None,John Grisham,Michael Beck,20 hrs and 46 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,25863.0,$35.00,2021-05-01,31.14
1,2021-05-01 00:00:03,561b26c1,829,United States of America,The 5 Love Languages of Children,The Secret to Loving Children Effectively,Gary Chapman,Chris Fabry,5 hrs and 48 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,2441.0,$19.59,2021-05-01,31.14
2,2021-05-01 00:00:04,81f149e5,1391,Japan,The Guardians,A Novel,John Grisham,Michael Beck,11 hrs and 50 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,26781.0,$31.50,2021-05-01,31.14
3,2021-05-01 00:00:07,4f218413,1586,Taiwan,How to Be a 3% Man,None,Corey Wayne,Corey Wayne,7 hrs and 33 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,11459.0,$19.95,2021-05-01,31.14
4,2021-05-01 00:00:18,a4066781,300,United States of America,Napoleon Hill's Outwitting the Devil,The Secret to Freedom and Success,Napoleon Hill,Dan John Miller,5 hrs and 51 mins,Unabridged Audiobook,Business & Careers,4.8,9305.0,$17.49,2021-05-01,31.14

Right now we got all data in one table but we have to know price in that time by multpling two column which are Price and conversion_rate, before hand we must chage type Price column to string or change $ it out.

In [83]:
final_df['Price'] = final_df.apply(lambda x: x["Price"].replace("$",""), axis=1) #lambda x is define x to be variable table after : x is mean table and ["Price"] is column / axix =  mean do only that column
final_df['Price'] = final_df['Price'].astype(float) # change type to float

In [84]:
final_df.head()

,timestamp,user_id,book_id,country,Book Title,Book Subtitle,Book Author,Book Narrator,Audio Runtime,Audiobook_Type,Categories,Rating,Total No. of Ratings,Price,date,conversion_rate
0,2021-05-01 00:00:01,ad8eca41,1584,Portugal,Sycamore Row,None,John Grisham,Michael Beck,20 hrs and 46 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,25863.0,35.00,2021-05-01,31.14
1,2021-05-01 00:00:03,561b26c1,829,United States of America,The 5 Love Languages of Children,The Secret to Loving Children Effectively,Gary Chapman,Chris Fabry,5 hrs and 48 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,2441.0,19.59,2021-05-01,31.14
2,2021-05-01 00:00:04,81f149e5,1391,Japan,The Guardians,A Novel,John Grisham,Michael Beck,11 hrs and 50 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,26781.0,31.50,2021-05-01,31.14
3,2021-05-01 00:00:07,4f218413,1586,Taiwan,How to Be a 3% Man,None,Corey Wayne,Corey Wayne,7 hrs and 33 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,11459.0,19.95,2021-05-01,31.14
4,2021-05-01 00:00:18,a4066781,300,United States of America,Napoleon Hill's Outwitting the Devil,The Secret to Freedom and Success,Napoleon Hill,Dan John Miller,5 hrs and 51 mins,Unabridged Audiobook,Business & Careers,4.8,9305.0,17.49,2021-05-01,31.14

In [85]:
final_df.dtypes #to check type all column in the table

timestamp               datetime64[ns]
user_id                         object
book_id                          int64
country                         object
Book Title                      object
Book Subtitle                   object
Book Author                     object
Book Narrator                   object
Audio Runtime                   object
Audiobook_Type                  object
Categories                      object
Rating                          object
Total No. of Ratings           float64
Price                          float64
date                            object
conversion_rate                float64
dtype: object

In [80]:
final_df['THBPrice'] = final_df['Price'] * final_df['conversion_rate']
final_df.head()

,timestamp,user_id,book_id,country,Book Title,Book Subtitle,Book Author,Book Narrator,Audio Runtime,Audiobook_Type,Categories,Rating,Total No. of Ratings,Price,date,conversion_rate,THBPrice
0,2021-05-01 00:00:01,ad8eca41,1584,Portugal,Sycamore Row,None,John Grisham,Michael Beck,20 hrs and 46 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,25863.0,35.00,2021-05-01,31.14,1089.9000
1,2021-05-01 00:00:03,561b26c1,829,United States of America,The 5 Love Languages of Children,The Secret to Loving Children Effectively,Gary Chapman,Chris Fabry,5 hrs and 48 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,2441.0,19.59,2021-05-01,31.14,610.0326
2,2021-05-01 00:00:04,81f149e5,1391,Japan,The Guardians,A Novel,John Grisham,Michael Beck,11 hrs and 50 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,26781.0,31.50,2021-05-01,31.14,980.9100
3,2021-05-01 00:00:07,4f218413,1586,Taiwan,How to Be a 3% Man,None,Corey Wayne,Corey Wayne,7 hrs and 33 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,11459.0,19.95,2021-05-01,31.14,621.2430
4,2021-05-01 00:00:18,a4066781,300,United States of America,Napoleon Hill's Outwitting the Devil,The Secret to Freedom and Success,Napoleon Hill,Dan John Miller,5 hrs and 51 mins,Unabridged Audiobook,Business & Careers,4.8,9305.0,17.49,2021-05-01,31.14,544.6386

Another way using def function

In [88]:
def conversion_rate(price, rate):
    return price * rate

#final_df["THBPrice"] = final_df.apply(lambda x: x["Price"] * x["conversion_rate"], axis=1)
#final_df["THBPrice"]

#or use def function
final_df["THBPrice"] = final_df.apply(lambda x: conversion_rate(x["Price"], x["conversion_rate"]), axis=1)
final_df

,timestamp,user_id,book_id,country,Book Title,Book Subtitle,Book Author,Book Narrator,Audio Runtime,Audiobook_Type,Categories,Rating,Total No. of Ratings,Price,conversion_rate,THBPrice
0,2021-05-01 00:00:01,ad8eca41,1584,Portugal,Sycamore Row,None,John Grisham,Michael Beck,20 hrs and 46 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,25863.0,35.00,31.140,1089.90000
1,2021-05-01 00:00:03,561b26c1,829,United States of America,The 5 Love Languages of Children,The Secret to Loving Children Effectively,Gary Chapman,Chris Fabry,5 hrs and 48 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,2441.0,19.59,31.140,610.03260
2,2021-05-01 00:00:04,81f149e5,1391,Japan,The Guardians,A Novel,John Grisham,Michael Beck,11 hrs and 50 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,26781.0,31.50,31.140,980.91000
3,2021-05-01 00:00:07,4f218413,1586,Taiwan,How to Be a 3% Man,None,Corey Wayne,Corey Wayne,7 hrs and 33 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,11459.0,19.95,31.140,621.24300
4,2021-05-01 00:00:18,a4066781,300,United States of America,Napoleon Hill's Outwitting the Devil,The Secret to Freedom and Success,Napoleon Hill,Dan John Miller,5 hrs and 51 mins,Unabridged Audiobook,Business & Careers,4.8,9305.0,17.49,31.140,544.63860
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1998816,2021-07-31 23:59:47,72da1411,600,Portugal,The Time of Contempt,"The Witcher, Book 2",Andrzej Sapkowski,Peter Kenny,11 hrs and 55 mins,Unabridged Audiobook,Science Fiction & Fantasy,4.7,14344.0,25.08,32.887,824.80596
1998817,2021-07-31 23:59:48,620c27c8,462,Montenegro,Endurance,Shackleton's Incredible Voyage,Alfred Lansing,Simon Prebble,10 hrs and 20 mins,Unabridged Audiobook,History,4.7,18764.0,24.95,32.887,820.53065
1998818,2021-07-31 23:59:55,84fe88ab,1656,United States of America,The Spy and the Traitor,The Greatest Espionage Story of the Cold War,Ben Macintyre,John Lee,13 hrs and 20 mins,Unabridged Audiobook,Biographies & Memoirs,4.8,7150.0,31.95,32.887,1050.73965
1998819,2021-07-31 23:59:57,fd6cc4fc,522,United States of America,Lilac Girls,A Novel,Martha Hall Kelly,Cassandra Campbell,17 hrs and 30 mins,Unabridged Audiobook,Literature & Fiction,4.7,19401.0,31.50,32.887,1035.94050
1998820,2021-07-31 23:59:59,9f4d5e3b,110,United States of America,Unfu*k Yourself,Get Out of Your Head and into Your Life,Gary John Bishop,Gary John Bishop,3 hrs and 24 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.6,73022.0,20.52,32.887,674.84124

we can drop column that's not neccessary such as date and timstamp
so axis = 1 mean drop column(if axis =0 it can use drop row)

In [90]:
final_df = final_df.drop("date", axis = 1)

KeyError: "['date'] not found in axis"

In [91]:
final_df

,timestamp,user_id,book_id,country,Book Title,Book Subtitle,Book Author,Book Narrator,Audio Runtime,Audiobook_Type,Categories,Rating,Total No. of Ratings,Price,conversion_rate,THBPrice
0,2021-05-01 00:00:01,ad8eca41,1584,Portugal,Sycamore Row,None,John Grisham,Michael Beck,20 hrs and 46 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,25863.0,35.00,31.140,1089.90000
1,2021-05-01 00:00:03,561b26c1,829,United States of America,The 5 Love Languages of Children,The Secret to Loving Children Effectively,Gary Chapman,Chris Fabry,5 hrs and 48 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,2441.0,19.59,31.140,610.03260
2,2021-05-01 00:00:04,81f149e5,1391,Japan,The Guardians,A Novel,John Grisham,Michael Beck,11 hrs and 50 mins,Unabridged Audiobook,"Mystery, Thriller & Suspense",4.6,26781.0,31.50,31.140,980.91000
3,2021-05-01 00:00:07,4f218413,1586,Taiwan,How to Be a 3% Man,None,Corey Wayne,Corey Wayne,7 hrs and 33 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.8,11459.0,19.95,31.140,621.24300
4,2021-05-01 00:00:18,a4066781,300,United States of America,Napoleon Hill's Outwitting the Devil,The Secret to Freedom and Success,Napoleon Hill,Dan John Miller,5 hrs and 51 mins,Unabridged Audiobook,Business & Careers,4.8,9305.0,17.49,31.140,544.63860
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1998816,2021-07-31 23:59:47,72da1411,600,Portugal,The Time of Contempt,"The Witcher, Book 2",Andrzej Sapkowski,Peter Kenny,11 hrs and 55 mins,Unabridged Audiobook,Science Fiction & Fantasy,4.7,14344.0,25.08,32.887,824.80596
1998817,2021-07-31 23:59:48,620c27c8,462,Montenegro,Endurance,Shackleton's Incredible Voyage,Alfred Lansing,Simon Prebble,10 hrs and 20 mins,Unabridged Audiobook,History,4.7,18764.0,24.95,32.887,820.53065
1998818,2021-07-31 23:59:55,84fe88ab,1656,United States of America,The Spy and the Traitor,The Greatest Espionage Story of the Cold War,Ben Macintyre,John Lee,13 hrs and 20 mins,Unabridged Audiobook,Biographies & Memoirs,4.8,7150.0,31.95,32.887,1050.73965
1998819,2021-07-31 23:59:57,fd6cc4fc,522,United States of America,Lilac Girls,A Novel,Martha Hall Kelly,Cassandra Campbell,17 hrs and 30 mins,Unabridged Audiobook,Literature & Fiction,4.7,19401.0,31.50,32.887,1035.94050
1998820,2021-07-31 23:59:59,9f4d5e3b,110,United States of America,Unfu*k Yourself,Get Out of Your Head and into Your Life,Gary John Bishop,Gary John Bishop,3 hrs and 24 mins,Unabridged Audiobook,"Relationships, Parenting & Personal Development",4.6,73022.0,20.52,32.887,674.84124

In [92]:
final_df.to_csv("output.csv", index=False) #we will use index = False to cut index in pandas out because when we export to csv it will show index but we don't need it

How to create .env

In [16]:
%%writefile .env
MYSQL_HOST = '...' #IP address for DB
MYSQL_PORT = 3306          # default for port MySQL
MYSQL_USER = '...'
MYSQL_PASSWORD = '...'
MYSQL_DB = '...'
MYSQL_CHARSET = '...'

Overwriting .env

In [17]:
class Config:
    MYSQL_HOST = os.getenv("MYSQL_HOST")
    MYSQL_PORT = os.getenv("MYSQL_PORT")           # default for port MySQL
    MYSQL_USER = os.getenv("MYSQL_USER")
    MYSQL_PASSWORD = os.getenv("MYSQL_PASSWORD")
    MYSQL_DB = os.getenv("MYSQL_DB")
    MYSQL_CHARSET = os.getenv("MYSQL_CHARSET")

In [18]:
Config.MYSQL_HOST

"'...' #IP address for DB"

In [19]:
os.getenv("MYSQL_PASSWORD")

'...'

how read .env by python-dotenv

In [1]:
!pip install python-dotenv

Requirement already satisfied: python-dotenv in c:\users\s.palakorn\anaconda3\lib\site-packages (1.0.0)

In [5]:
import os
from dotenv import load_dotenv
load_dotenv()

True

In [ ]:
!head